name: e2e

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '/readme.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '/readme.md'
  schedule:
    - cron: '45 7 * * *'

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
        # os: [ubuntu, macos, windows]
        browser: [firefox, firefoxesr]
        exclude:
          - os: windows
            browser: firefoxesr

    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install deps
      run: bun install

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ matrix.browser == 'firefox' && 'latest' || 'latest-esr' }}
  
    - name: Print Firefox version (Unix-like)
      if: matrix.os == 'ubuntu' || matrix.os == 'macos'
      run: firefox --version

    - name: Build and test (Firefox)
      uses: nick-fields/retry@v3
      env:
        HEADLESS: 1
      with: 
        max_attempts: ${{ github.event_name == 'pull_request' && 5 || 10 }}
        timeout_minutes: 10
        retry_wait_seconds: 10
        shell: bash
        command: |
          bun run clean && bun run build --old-native && bun make-zip && bun jest
